version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  app:
    build: ./backend
    restart: always
    ports:
      - "50100:50100"
    depends_on:
      - db
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:5432"]
        interval: 30s
        timeout: 10s
        retries: 5

  frontend:
    build: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - app



