version: '3.1'

services:
  app:
    image: taskapp.azurecr.io/backend
    build: ./backend
    restart: always
    ports:
      - "80:50100"

  frontend:
    image: taskapp.azurecr.io/frontend
    build: .
    restart: always
    ports:
      - "80:8000"
    depends_on:
      - app



