on:
  push:
    branches:
      - master
      - feature/*
  pull_request:
      types: [opened, synchronize, reopened]
name: Main Workflow
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    environment: Sonar
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        projectBaseDir: .
        args: >
          -Dsonar.python.coverage.reportPaths=coverage.xml
          -Dsonar.sources=./**
          -Dsonar.test.exclusions=tests/**
          -Dsonar.tests=tests/
          -Dsonar.verbose=true
          -Dsonar.python.version=3.7
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
