on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
      types: [opened, synchronize, reopened]
name: Main Workflow
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    container:
      image: python:3.7
    environment: Sonar
    steps:
    - uses: actions/checkout@v3
    - name: Python test
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
        pip install pytest pytest-cov Flask-Testing
        coverage run -m pytest backend/tests
        coverage xml -o coverage.xml        
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
